language: node_js

node_js:
  - "stable"

cache:
  npm: false

script:
  - npm run build

before_deploy:
  - cd examples/demo-app
  - npm run build

deploy:
  provider: pages
  local_dir: examples/demo-app/build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
